#!/bin/bash
cp proj_multilingual_text_classification/docker/check_env.sh proj_multilingual_text_classification/docker/$DOCKERFILE/.
cp proj_multilingual_text_classification/docker/entrypoint.sh proj_multilingual_text_classification/docker/$DOCKERFILE/.
cp -r proj_multilingual_text_classification/src proj_multilingual_text_classification/docker/$DOCKERFILE/.
cp proj_multilingual_text_classification/env/environment.yaml proj_multilingual_text_classification/docker/$DOCKERFILE/.