name: env_multilingual_class
channels:
- defaults
- conda-forge
dependencies:
# core packages
- python=3.7.6
- ipykernel=5.1.4
- pip=20.0.2
- nbdime=1.1.0 #conda-forge
- joblib=0.14.1
# data processing
- numpy=1.18.1
- pandas=1.0.1
# data visualization
- plotly=4.5.0
- matplotlib=3.1.3
# machine learning
- lime=0.1.1.37 #conda-forge
- scikit-learn=0.22.1
# machine learning - nlp
- nltk=3.4.5
- gensim=3.8.0
- spacy=2.2.3 #conda-forge
- langdetect=1.0.7 #conda-forge
# code audit
- psutil=5.6.7
- pympler=0.8 #conda-forge
- watermark=2.0.2 #conda-forge
- pylint=2.4.4
- pytest=5.3.5
- autopep8=1.4.4
- pep8=1.7.1
- pylama=7.7.1 #conda-forge
# gcp client libraries [check beam-sdk for gcp dependency] https://beam.apache.org/documentation/sdks/python-dependencies/
- google-cloud-storage=1.26.0 #conda-forge #apache-beam[gcp]==2.18.0
- google-cloud-bigquery=1.24.0 #conda-forge #apache-beam[gcp]==2.18.0
#- google-auth=1.10.0
#- google-api-core=1.15
- pip:
  # data processing
  - apache-beam[gcp]==2.18.0
  # data visualization
  - facets-overview==1.0.0
  # machine learning
  - xgboost==1.0.1
  - tensorflow==2.1.0
  - tensorflow-hub==0.7.0
  - tensorflow-datasets==2.1.0
  - tensorflow-text==2.1.0rc0
  - tensorflow-addons==0.7.1
  - cloudml-hypertune==0.1.0.dev6
  # machine learning - nlp
  # EN core trained on web small size(sm) (exist md:medium or ld:large)
  - "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz#egg=en_core_web_sm==2.2.5"
  # IT core trained on news small size(sm)
  - "https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-2.2.5/it_core_news_sm-2.2.5.tar.gz#egg=it_core_news_sm==2.2.5"
  # FR core trained on news small size(sm) (exist md:medium)
  - "https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-2.2.5/fr_core_news_sm-2.2.5.tar.gz#egg=fr_core_news_sm==2.2.5"
  # DE core trained on news small size(sm) (exist md:medium)
  - "https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.2.5/de_core_news_sm-2.2.5.tar.gz#egg=de_core_news_sm==2.2.5"
  # machine learning - framework
  - tfx==0.21.0
  # gcp client libraries
  #- google-cloud-dlp==0.12.1
  #- google-cloud-pubsub==1.0.2 #apache-beam[gcp]==2.16.0
  #- google-cloud-videointelligence==1.11.0
  #- google-cloud-logging==1.14.0
  #- google-cloud-dns==0.31.0
  #- google-cloud-resource-manager==0.30.0
  #- google-cloud-speech==1.3.1
  #- google-cloud-vision==0.41.0
  #- google-cloud-firestore==1.6.0
  #- google-cloud-bigtable==1.0.0 #apache-beam[gcp]==2.16.0
  #- google-cloud-translate==2.0.0
  #- google-cloud-spanner==1.13.0
  #- google-cloud-error-reporting==0.33.0
  #- google-cloud-monitoring==0.34.0
  #- google-cloud==0.34.0
  #- google-cloud-trace==0.23.0
  #- google-cloud-datastore==1.7.4
  - grpcio #issue with TensorBoard