# compare to ml-engine runtimes
# https://cloud.google.com/ml-engine/docs/tensorflow/runtime-version-list
name: env_gcp_dl
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- numpy=1.16
- scipy=1.2
- scikit-learn=0.20
- scikit-image
#- tornado=5.1
#- jupyter
#- jupyterlab
#- jupyter_contrib_nbextensions
#- jupyter_nbextensions_configurator
- pandas=0.24
- matplotlib=2.1.0
#- nomkl # Only for Mac user
#- notebook
- ipykernel
#- ipywidgets
#- nbconvert
- tensorflow=1.13
- tensorboard=1.13
- watermark
- pytest
- autopep8
- pylint
- pep8
- pylama
#- nbdime
- pip
- google-auth
- pillow
- seaborn
- lime
- google-cloud-storage
- google-cloud-bigquery
- rise
- pyyaml=3.12
- pip:
    - apache-beam[gcp]
    - google-cloud-storage
    - google-cloud-core==0.29
    - google-cloud-bigquery[pandas]
    - google-cloud-bigquery-storage[fastavro,pandas]