steps:

# Clone github repository
- name: 'gcr.io/cloud-builders/git'
  args: 
  - 'clone'
  - 'https://github.com/tarrade/proj_multilingual_text_classification'
  id: 'clone_github'

## step 1: base CPU
# Copy configuration files
- name: 'debian'
  args:
  - 'bash'
  - 'proj_multilingual_text_classification/docker/${_DOCKERFILE}/copy_files.sh'
  env:
  - 'DOCKERFILE=${_DOCKERFILE}'
  id: 'copy_files'

# Set and print env variables for its execution
- name: 'debian'
  args: 
  - 'bash'
  - 'check_env.sh'
  env:
  - 'PROJECT=$PROJECT_ID'
  - 'TAG=${_TAG}'
  - 'DOCKERFILE=${_DOCKERFILE}'
  id: 'check_env_variables'
  dir: 'proj_multilingual_text_classification/docker/${_DOCKERFILE}'
  waitFor: ['copy_files']

# Check the config of Docker
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'info'
  id: 'check_config_docker'
  waitFor: ['check_env_variables']

## Restore cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'if [ ${_BUILD} == "true" ]; then docker pull gcr.io/$PROJECT_ID/${_DOCKERFILE}:latest || exit 0; fi'
  id: 'restore_cache_from_container_registry'
  waitFor: ['check_config_docker']

## Build docker image with the tag
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'if [ ${_BUILD} == "true" ]; then docker build -t gcr.io/$PROJECT_ID/${_DOCKERFILE}:${_TAG} -t gcr.io/$PROJECT_ID/${_DOCKERFILE}:latest --cache-from gcr.io/$PROJECT_ID/${_DOCKERFILE}:latest . ; fi'
  id: 'build_docker_image'
  dir: 'proj_multilingual_text_classification/docker/${_DOCKERFILE}'
  waitFor: ['restore_cache_from_container_registry']

## Push image in Container Registry with a tag and latest
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'if [ ${_BUILD} == "true" ]; then docker push gcr.io/$PROJECT_ID/${_DOCKERFILE}; fi'
  id: 'push_image_container_registry'
  waitFor: ['build_docker_image']

## Check if a give tag of an image exist in Container Registry with a given tag
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'tag=$(gcloud container images list-tags --filter="tags:${_TAG}" --format=json gcr.io/$PROJECT_ID/${_DOCKERFILE}); echo $tag; if [ "$tag" == [] ]; then echo "no tag!"; exit 1; else echo "the tag exist" ; fi'
  id: 'check_tag_image_exist_container_registry'
  waitFor: ['push_image_container_registry']
## end step 1: base CPU

## final step

## Check sizes of the images
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'if [ ${_BUILD} == "true" ]; then docker images ; fi'
  id: 'check_size_all_images'
  waitFor: ['check_tag_image_exist_container_registry']

substitutions:
    _TAG: dev
    _DOCKERFILE: derived-pytorch-cpu
    _BUILD: none

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 2h00m0s